title: ChrisCrossCrash Docs
# description: >- # this means to ignore newlines until "baseurl:"
#   Welcome to my personal documentation website. I use it as a reference for
#   myself and to share with others. In it, you will find my work methodology,
#   as well as my personal notes on various topics.
github_username: ChrisCrossCrash
theme: minima
source: docs
